### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 513: ordinal not in range(256)

### ISSUE THREAD

**Issue by YugiPeep** [rimonhanna/Spotify-To-Youtube#16]

**Comment by pha1n0q** [comment]
I know it's literally been more than a year, but since you closed this issue, did you ever find out how to fix the error?

**Comment by YugiPeep** [comment]
> I know it's literally been more than a year, but since you closed this issue, did you ever find out how to fix the error?

I couldn't fix the error, but i found a better alternative. Its a desktop app called [Free Your Music](https://freeyourmusic.com/). It was way easier for me to use, but make sure to retry with any songs it didnt get right. The 2nd attempt it did got everything right.
