### ISSUE TITLE
Not idiot proof.

### ISSUE THREAD

**Issue by matthewhoth** [rimonhanna/Spotify-To-Youtube#5]
Great app. Maybe add a short line about the Spotify config needs the ID while the Youtube config needs a name.

Yes, it is laid out in the code. But some bums like me might not notice. 

Also a note that by default the transfer is limited to 100 songs.

(Spotify ID - A base-62 number that you can find at the end of the Spotify URI (see above) for an artist, track, album, etc. Example: 6rqhFgbbKwnb9MLmUQDhG6)

**Comment by rimonhanna** [comment]
Thanks for the feedback, I'll update the readme!
