### ISSUE TITLE
Songs getting added again if playlist has more than 100 songs.

### ISSUE THREAD

**Issue by aksh1t** [rimonhanna/Spotify-To-Youtube#6]
Great script by the way! 

In the following line:

https://github.com/rimonhanna/Spotify-To-Youtube/blob/5e5806428e00125db814db599332730c1d4291dc/spotifyToYoutube.py#L31

we are not using the `offset` parameter in the `user_playlist_tracks` method. This causes the same songs to be looped again after the 100 limit. We should be using `offset=counter` as a param there.

**Comment by rimonhanna** [comment]
thanks for pointing it out, should be fixed now!
