### ISSUE TITLE
Having issue with login_to_google() 

### ISSUE THREAD

**Issue by unwan878** [rimonhanna/Spotify-To-Youtube#7]
Traceback (most recent call last):
  File "C:\Users\vm\Desktop\Spotify-To-Youtube-main\runLocally.py", line 35, in <module>
    ytmusic = spotifyToYoutube.login_to_google()
TypeError: login_to_google() missing 1 required positional argument: 'ytmusic_headers'

I 100% sure that the cookie are correct as it can work at your site, but it only transfer only until around 600songs, so i tried the hard way, but no luck with it.

**Comment by akabrun** [comment]
I had the same issue. I fixed it like so:

Open the "runLocally.py" file with notepad++ or any code editing app of your choice,
Scroll down to line 35,
Change `ytmusic = spotifyToYoutube.login_to_google()` 
into `ytmusic = spotifyToYoutube.login_to_google('ytmusic_headers.json')`

![ss](https://user-images.githubusercontent.com/30055017/179335734-382e28b8-c42f-4ece-99cd-933174b3dc57.png)

Save the file,

Now try the command and it should work :)

**Comment by rimonhanna** [comment]
Thanks for bringing this to my attention, PR has been merged
